[features]
seeds = false
skip-lint = false
[programs.localnet]
incrementer = "GvPfxfmBawKYNKNhXf2wg1HpG4s1KSEFwapfQg8YLtnd"
latest_round = "5iDtDHjXP7PcNbTQWSj8bfKm7tU6MhvsHGYXdqpcDZgR"

[provider]
cluster = "localnet"
wallet = "/Users/imiml/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
